Search: Add support for dynamic facets
answear/luigis-box-bundle pull request #44
Opened 2023-09-06 10:51 UTC by cuchac

Add support for Dynamic Facets to Search

https://docs.luigisbox.com/#search-as-a-service-json-api

2023-09-07 08:56 UTC, lukasz-falda requested changes
Great update!

But please update SearchUrlBuilderTest too.

2023-09-08 08:48 UTC, cuchac commented
Tests present

2023-09-08 09:43 UTC, lukasz-falda approved these changes

2023-09-08 09:48 UTC, mglowala approved these changes

2023-09-08 09:51 UTC, merged